import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  Facebook,
  Instagram,
  Linkedin,
  Send,
  Twitter,
  Youtube,
} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trade Pro",
  description: "Generated by create next app",
};

const Footer = () => (
  <div className="bg-black text-white py-8">
    <div className="container mx-auto px-4">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
        <div>
          <p className="text-sm mb-2">Tech Park, 4th Floor</p>
          <p className="text-sm mb-2">CyberHub Road, Bangalore</p>
          <p className="text-sm mb-2">Bangalore - 201204</p>
          <p className="text-sm mb-2">
            <a href="" className="text-blue-500 hover:underline">
              Contact Us
            </a>
          </p>
          <div className="flex space-x-4 pt-2">
            <Facebook
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={24}
            />
            <Twitter
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={24}
            />
            <Youtube
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={24}
            />
            <Instagram
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={24}
            />
            <Linkedin
              className="text-gray-400 hover:text-blue-500 cursor-pointer"
              size={24}
            />
            <Send />
          </div>
        </div>
        <div>
          <h3 className="font-semibold mb-4">Products</h3>
          <ul className="space-y-2">
            {["Stocks", "Futures & Options", "IPO", "Mutual Funds"].map(
              (item) => (
                <li
                  className="text-sm hover:text-blue-500 cursor-pointer"
                  key={item}
                >
                  {item}
                </li>
              )
            )}
          </ul>
        </div>
        <div>
          <h3 className="font-semibold mb-4 ">TradePro</h3>
          <ul className="space-y-2">
            {["About Us", "Pricing", "Blog", "Career", "Help & Support"].map(
              (item) => (
                <li
                  className="text-sm hover:text-blue-500 cursor-pointer"
                  key={item}
                >
                  {item}
                </li>
              )
            )}
          </ul>
        </div>
        <div>
          <h3 className="font-semibold mb-4">Quick Links</h3>
          <ul className="space-y-2">
            {[
              "AMC Mutual Funds",
              "Calculator",
              "Glossary",
              "TradePro Digest",
            ].map((item) => (
              <li
                className="text-sm hover:text-blue-500 cursor-pointer"
                key={item}
              >
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
      <div className="mt-8 pt-8 border-gray-200 flex flex-col md:flex-row justify-between items-center">
        <p className="text-sm text-gray-500 mb-4 md:mb-0">
          © 2016 - 2024 TradePro. All Rights Reserved, Built with ❤️ in India
        </p>
      </div>
    </div>
  </div>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}